### ISSUE TITLE
Improvement: Validate Title and Dedup

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther_analysis_tool#14]
## Description

Users should have confidence that their title and deduplication functions will work just like the `rule()`/`policy()` functions.

## Acceptance Criteria

When running unit tests on rules/policies, check if the `title()` and `dedup()` are defined, and then ensure `KeyError`s isn't thrown and `None` is not present in the string.

**Comment by kostaspap** [comment]
This is a good idea. Any recommendation on how the success/failure should be displayed?

**Comment by nhakmiller** [comment]
I like this, although I don't agree with validating the `None` is not present in the string. I think there are lots of reasons for `None` to be present, I think we should validate that the `title` and `dedup` functions are valid python, don't raise an error, and return a string.

**Comment by nhakmiller** [comment]
This has been implemented, rules that return True now also print out the dedup and title output to the console. This accomplishes both validation that there are no errors in those functions, and also allows manual verification that the output looks as intended.
