### ISSUE TITLE
Skip Empty Folders

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther_analysis_tool#15]
When running the tool on a folder with no files, a message should return indicating there were no analysis files to test. Right now, the tool still runs "successfully":

```
$ panther_analysis_tool test --path /tmp
[INFO]: Testing analysis packs in /tmp
```

**Comment by jacknagz** [comment]
@nhakmiller is this still an issue? I believe we did this already

**Comment by nhakmiller** [comment]
Yeah we're doing this now:

```
% panther_analysis_tool test --path meme
[INFO]: Testing analysis packs in meme

[ERROR]: ['Nothing to test in meme']
```
