### ISSUE TITLE
Bug: Rule Error Handling

### ISSUE THREAD

**Issue by jacknagz** [panther-labs/panther_analysis_tool#23]
While using the PAT, I noticed if the rule throws an error, the help message is printed:

```
$ panther_analysis_tool test --path gcp_audit_rules_e/
[INFO]: Testing analysis packs in gcp_audit_rules_e/

GCP.ConfigChanges
	[PASS] Instance Change

GCP.MyRuleID
usage: panther_analysis_tool [-h] [--version] {test,zip,upload} ...

Panther Analysis Tool: A command line tool for managing Panther policies and
rules.

positional arguments:
  {test,zip,upload}
    test             Validate analysis specifications and run policy and rule
                     tests.
    zip              Create an archive of local policies and rules for
                     uploading to Panther.
    upload           Upload specified policies and rules to a Panther
                     deployment.

optional arguments:
  -h, --help         show this help message and exit
  --version          show program's version number and exit
```

The only way I can troubleshoot is by printing to step through the rule. We should respond with ERROR if this case happens.

**Comment by jacknagz** [comment]
@nhakmiller this was resolved IIRC, right?

**Comment by nhakmiller** [comment]
I believe we've resolved the majority of this, but after fixing it we still heard feedback from a few users about running into this issue. I haven't heard anything recently so it could just be a matter of users not upgrading or something. At the very least we've fixed the majority of it, I suppose any new instances of this issue could be raised as new bug reports.
