### ISSUE TITLE
Support mocking

### ISSUE THREAD

**Issue by austinbyers** [panther-labs/panther_analysis_tool#30]
We are increasingly encouraging users to write rules which leverage external APIs - our own key-value store is a good example. But these rules cannot easily be unit tested today without triggering the real API calls.

## Implementation
Python is relatively easy to [patch](https://docs.python.org/3/library/unittest.mock.html#patch) - given a method/class as a string, you can turn it into a MagicMock object.

So the implementation may be as simple as adding a list of mock targets to a test definition, and then starting each mock before running the appropriate test. Mocks may need to be key/value pairs so the user can configure the return value of the mock.

Rather than defining the mocks in the test config, another option could be to add a `test_setup` function or similar as part of the Python body that would be triggered before every unit test. (Similar to our `dedup` and `alert_title` functions.) This way, users could leverage the entire mock library and make it as complex as they need to.

However we choose to implement it, we need to do the same thing in the Panther backend if we want to be able to run mocked unit tests from the web app. And, in that case, we would need frontend changes so users could define mocks from the test editing view

## Workaround

It is possible to write these rules, but the main body has to explicitly check if it's running in a test:

```python
BUCKET = None

def rule(event):
    if not event['Field'].startswith('___test___') and not BUCKET:
        # Lazy initialize client
        BUCKET = boto3.resource('s3').Bucket('my-bucket')
    result = event['Field'] == 'needs-alert'

    if result and BUCKET is not None:
        # External API call (will not run in tests)
        BUCKET.put_object(...)
    return result
```

This only works if the test data has some defining characteristic that would not happen in real data. One alternative to proper mocking could be to simply introduce a "TESTING" environment variable so that rules can check if they're running in test mode.

**Comment by rleighton** [comment]
Is pytest an option?

**Comment by jacknagz** [comment]
> Python is relatively easy to patch - given a method/class as a string, you can turn it into a MagicMock object. So the implementation may be as simple as adding a list of mock targets to a test definition and then starting each mock before running the appropriate test. Mocks may need to be key/value pairs so the user can configure the return value of the mock.

I like this option, and if possible we should implement it in the short term to unblock local development. It also works well because different tests should expect different results.

**Comment by jacknagz** [comment]
@wey-chiang are we using the original body of this ticket for the implementation of this feature? Or can we delete it/move it to the RFC? This ticket should just be a story for the feature we are implementing, the acceptance criteria, and the technical implementation:

https://github.com/panther-labs/panther/blob/master/.github/ISSUE_TEMPLATE/story.md

The Stories can be taken from the Epic

cc @mattthetraveler

**Comment by wey-chiang** [comment]
Closing this out and creating new tickets for the implementation within Panther and PAT
