### ISSUE TITLE
logtype and resourcetype validation

### ISSUE THREAD

**Issue by lindsey-w** [panther-labs/panther_analysis_tool#73]
### Describe the bug
When validating the specification file of a detection, the panther_analysis_tool does not validate the `LogTypes` and `DetectionTypes` fields. The panther backend does validate this. We should be sure that the logtype and resource types only pass schema validation if the values given are in the set of supported resource and log types.  **Note: special consideration might need to be taken into account for custom logtypes/schemas.

### Steps to reproduce

Create a rule or policy with an invalid logtype or resourcetype
Upload this rule/policy to Panther with Pat
See an error for invalid logtype or resourcetype
Expected behavior
Pat should catch this inappropriate specification file before trying to upload it, and report to the user the issue in a useful manner.

### Additional context
First reported [here](https://github.com/panther-labs/panther-analysis/pull/193#issuecomment-778321039)

**Comment by kostaspap** [comment]
I don't think it's possible to validate log types without talking to backend. Log Types are not static - users can create their own log types through the UI. @lindsey-w
